version: '3.4'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

  b3digitas.api:
    image: ${DOCKER_REGISTRY-}b3digitasapi
    build:
      context: .
      dockerfile: B3Digitas/Dockerfile

  b3digitas.consumerwebsite:
    image: ${DOCKER_REGISTRY-}b3digitasconsumerwebsite
    build:
      context: .
      dockerfile: ConsumerWebSite-ConsoleApp/Dockerfile

